"""initial_schema

Revision ID: 0ba9ffaa3170
Revises: None
Create Date: 2026-09-30 19:04:41.543061

"""

from collections.abc import Sequence

import pgvector
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0ba9ffaa3170"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "disruption_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "port_strike",
                "severe_weather",
                "geopolitical",
                "factory_fire",
                "cyber_attack",
                "customs_delay",
                "supplier_insolvency",
                "capacity_shortage",
                name="disruption_event_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum(
                "low",
                "medium",
                "high",
                "critical",
                name="disruption_event_severity",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("region", sa.String(length=200), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "country ~ '^[A-Z]{2}$'", name=op.f("ck_disruption_events_country_format")
        ),
        sa.CheckConstraint(
            "ended_at IS NULL OR ended_at >= started_at",
            name=op.f("ck_disruption_events_ended_after_started"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_disruption_events")),
    )
    op.create_index(
        "ix_disruption_events_open_country_region",
        "disruption_events",
        ["country", "region"],
        unique=False,
        postgresql_where=sa.text("ended_at IS NULL"),
    )
    op.create_table(
        "document_chunks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_ref", sa.String(length=300), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "chunk_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "chunk_index >= 0", name=op.f("ck_document_chunks_chunk_index_non_negative")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_chunks")),
        sa.UniqueConstraint(
            "source_ref", "chunk_index", name="uq_document_chunks_source_ref_chunk_index"
        ),
    )
    op.create_table(
        "parts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sku", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("is_critical", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.CheckConstraint("unit_cost >= 0", name=op.f("ck_parts_unit_cost_non_negative")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_parts")),
        sa.UniqueConstraint("sku", name=op.f("uq_parts_sku")),
    )
    op.create_table(
        "suppliers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("region", sa.String(length=200), nullable=False),
        sa.Column(
            "tier",
            sa.Enum("tier_1", "tier_2", "tier_3", name="supplier_tier", native_enum=False),
            nullable=False,
        ),
        sa.Column("reliability_score", sa.Float(), nullable=False),
        sa.CheckConstraint("country ~ '^[A-Z]{2}$'", name=op.f("ck_suppliers_country_format")),
        sa.CheckConstraint(
            "reliability_score BETWEEN 0 AND 1", name=op.f("ck_suppliers_reliability_range")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_suppliers")),
    )
    op.create_index("ix_suppliers_country_region", "suppliers", ["country", "region"], unique=False)
    op.create_table(
        "warehouses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("region", sa.String(length=200), nullable=False),
        sa.CheckConstraint("country ~ '^[A-Z]{2}$'", name=op.f("ck_warehouses_country_format")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_warehouses")),
    )
    op.create_index(
        "ix_warehouses_country_region", "warehouses", ["country", "region"], unique=False
    )
    op.create_table(
        "inventory",
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("part_id", sa.Uuid(), nullable=False),
        sa.Column("quantity_on_hand", sa.Integer(), nullable=False),
        sa.Column("reorder_point", sa.Integer(), nullable=False),
        sa.Column("daily_demand", sa.Float(), nullable=False),
        sa.CheckConstraint(
            "daily_demand >= 0", name=op.f("ck_inventory_daily_demand_non_negative")
        ),
        sa.CheckConstraint(
            "quantity_on_hand >= 0", name=op.f("ck_inventory_quantity_non_negative")
        ),
        sa.CheckConstraint(
            "reorder_point >= 0", name=op.f("ck_inventory_reorder_point_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["part_id"], ["parts.id"], name=op.f("fk_inventory_part_id_parts"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_inventory_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("warehouse_id", "part_id", name=op.f("pk_inventory")),
    )
    op.create_index("ix_inventory_part_id", "inventory", ["part_id"], unique=False)
    op.create_table(
        "purchase_orders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=False),
        sa.Column("part_id", sa.Uuid(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "submitted",
                "confirmed",
                "partially_received",
                "received",
                "cancelled",
                name="purchase_order_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("ordered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expected_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "expected_at >= ordered_at", name=op.f("ck_purchase_orders_expected_after_ordered")
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_purchase_orders_quantity_positive")),
        sa.CheckConstraint(
            "unit_price >= 0", name=op.f("ck_purchase_orders_unit_price_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["part_id"],
            ["parts.id"],
            name=op.f("fk_purchase_orders_part_id_parts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
            name=op.f("fk_purchase_orders_supplier_id_suppliers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_purchase_orders_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_orders")),
    )
    op.create_index("ix_purchase_orders_part_id", "purchase_orders", ["part_id"], unique=False)
    op.create_index(
        "ix_purchase_orders_supplier_id", "purchase_orders", ["supplier_id"], unique=False
    )
    op.create_index(
        "ix_purchase_orders_warehouse_id", "purchase_orders", ["warehouse_id"], unique=False
    )
    op.create_table(
        "supplier_parts",
        sa.Column("supplier_id", sa.Uuid(), nullable=False),
        sa.Column("part_id", sa.Uuid(), nullable=False),
        sa.Column("lead_time_days", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("is_primary", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.CheckConstraint("lead_time_days > 0", name=op.f("ck_supplier_parts_lead_time_positive")),
        sa.CheckConstraint(
            "unit_price >= 0", name=op.f("ck_supplier_parts_unit_price_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["part_id"],
            ["parts.id"],
            name=op.f("fk_supplier_parts_part_id_parts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
            name=op.f("fk_supplier_parts_supplier_id_suppliers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("supplier_id", "part_id", name=op.f("pk_supplier_parts")),
    )
    op.create_index("ix_supplier_parts_part_id", "supplier_parts", ["part_id"], unique=False)
    op.create_table(
        "shipments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("purchase_order_id", sa.Uuid(), nullable=False),
        sa.Column(
            "mode",
            sa.Enum(
                "sea", "air", "road", "rail", name="shipment_transport_mode", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "planned",
                "in_transit",
                "at_port",
                "delayed",
                "delivered",
                "cancelled",
                name="shipment_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("origin_port", sa.String(length=200), nullable=False),
        sa.Column("destination_port", sa.String(length=200), nullable=False),
        sa.Column("planned_eta", sa.DateTime(timezone=True), nullable=False),
        sa.Column("current_eta", sa.DateTime(timezone=True), nullable=False),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(status = 'delivered') = (delivered_at IS NOT NULL)",
            name=op.f("ck_shipments_delivered_at_matches_status"),
        ),
        sa.ForeignKeyConstraint(
            ["purchase_order_id"],
            ["purchase_orders.id"],
            name=op.f("fk_shipments_purchase_order_id_purchase_orders"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shipments")),
    )
    op.create_index(
        "ix_shipments_purchase_order_id", "shipments", ["purchase_order_id"], unique=False
    )
    op.create_index("ix_shipments_status", "shipments", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_shipments_status", table_name="shipments")
    op.drop_index("ix_shipments_purchase_order_id", table_name="shipments")
    op.drop_table("shipments")
    op.drop_index("ix_supplier_parts_part_id", table_name="supplier_parts")
    op.drop_table("supplier_parts")
    op.drop_index("ix_purchase_orders_warehouse_id", table_name="purchase_orders")
    op.drop_index("ix_purchase_orders_supplier_id", table_name="purchase_orders")
    op.drop_index("ix_purchase_orders_part_id", table_name="purchase_orders")
    op.drop_table("purchase_orders")
    op.drop_index("ix_inventory_part_id", table_name="inventory")
    op.drop_table("inventory")
    op.drop_index("ix_warehouses_country_region", table_name="warehouses")
    op.drop_table("warehouses")
    op.drop_index("ix_suppliers_country_region", table_name="suppliers")
    op.drop_table("suppliers")
    op.drop_table("parts")
    op.drop_table("document_chunks")
    op.drop_index(
        "ix_disruption_events_open_country_region",
        table_name="disruption_events",
        postgresql_where=sa.text("ended_at IS NULL"),
    )
    op.drop_table("disruption_events")
    # ### end Alembic commands ###
